In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

2.1.3


In [ ]:
array=np.array([1,2,3,4])
print(array)
print(type(array))
print(array*2)

[1 2 3 4]
<class 'numpy.ndarray'>
[2 4 6 8]


In [ ]:
print(array.ndim)

1


In [ ]:
matrix=np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix.ndim)

2


In [ ]:
print(matrix.shape)

(3, 3)


In [ ]:
print(matrix[0][0])#chain indexing
print(matrix[0,0])#multidimensional indexing

1
1


In [ ]:
array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                   [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                   [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y','Z',' ']]])
word=array[2,0,0]+array[1,1,1]+array[1,1,2]+array[2,1,1]
print(word)
                   

SNOW


In [ ]:
#slicing
array=np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12],
               [13,14,15,16]])
#array[start:stop:step]
print(array[0:4])
print(array[0:4:2])#2-step
print(array[::-1])#reverse

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
print(array[:,0])
print(array[:, 0:3])
print(array[:, ::2])
print(array[:, ::-1])
print(array[:, ::-2])
print(array[0:2, 0:2])#1st Quadrant

[ 1  5  9 13]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
[[ 4  2]
 [ 8  6]
 [12 10]
 [16 14]]
[[1 2]
 [5 6]]


In [ ]:
#Scalar Arithmetic
array=np.array([1,2,3])
print(array+1)
print(array-2)
print(array*3)
print(array/4)
print(array**5)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [ ]:
print(np.sqrt(array))

[1.         1.41421356 1.73205081]


In [ ]:
print(np.sqrt(array).round())

[1. 1. 2.]


In [ ]:
print(np.round(np.sqrt(array)))
print(np.ceil(np.sqrt(array)))
print(np.floor(np.sqrt(array)))
print(np.pi)

[1. 1. 2.]
[1. 2. 2.]
[1. 1. 1.]
3.141592653589793


In [ ]:
#Vectorized math functions
radii=np.array([1,2,3])
print(np.pi*radii**2)

[ 3.14159265 12.56637061 28.27433388]


In [ ]:
#Elementwise arithmetic
array1=np.array([1,2,3])
array2=np.array([4,5,6])
print(array1+array2)
print(array1-array2)
print(array1*array2)
print(array1/array2)
print(array1**array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [ ]:
#Comparision Operators
scores=np.array([91, 55, 60, 100, 78, 90])
print(scores==100)
print(scores>=60)
print(scores<=60)
scores[scores<60]=0
print(scores)

[False False False  True False False]
[ True False  True  True  True  True]
[False  True  True False False False]
[ 91   0  60 100  78  90]


In [ ]:
#Broadcasting:
#It allows performing operations on arrays with different shapes by virtually expanding dimensions
#so they match the larger array's shape

#the dimensions have the same size
#or
#one of the dimensions has a size of 1

In [ ]:
array1=np.array([[1,2,3,4]])
array2=np.array([[1],[2],[3],[4]])
print(array1.shape)
print(array2.shape)
print(array1*array2)

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [ ]:
array1=np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])
array2=np.array([[1],[2],[3],[4]])
print(array1.shape)
print(array2.shape)
print(array1*array2)

(4, 4)
(4, 1)
[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]
 [52 56 60 64]]


In [ ]:
#Multiplication Table
array1=np.array([[1,2,3,4,5,6,7,8,9,10]])
array2=np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])
print(array1*array2)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [ ]:
#Aggregate Functions: summarize data and typically return a single value

In [ ]:
array=np.array([[1,2,3,4,5],
               [6,7,8,9,10]])
print(np.sum(array))#sum
print(np.mean(array))#mean
print(np.std(array))#standard deviation
print(np.var(array))#variance
print(np.min(array))#min value
print(np.max(array))#max value
print(np.argmin(array))#position of min value
print(np.argmax(array))#position of max value
print(np.sum(array, axis=0))#column sum
print(np.sum(array, axis=1))#row sum

55
5.5
2.8722813232690143
8.25
1
10
0
9
[ 7  9 11 13 15]
[15 40]


In [ ]:
#Filtering:
#It is the process that helps pick out elements that satisfy a certain required condition

In [ ]:
ages=np.array([[21,17,19,20,28,30,65,16],
               [39,22,15,18,19,99,20,32]])
teenagers=ages[ages<18]
print(teenagers)
adults=ages[(ages>18) & (ages<65)]
print(adults)
seniors=ages[(ages<=100) & (ages>=65)]
print(seniors)
evens=ages[ages%2==0]
print(evens)
odds=ages[ages%2!=0]
print(odds)


[17 16 15]
[21 19 20 28 30 39 22 19 20 32]
[65 99]
[20 28 30 16 22 18 20 32]
[21 17 19 65 39 15 19 99]


In [ ]:
ages=np.array([[21,17,19,20,28,30,65,16],
               [39,22,15,18,19,99,20,32]])
adults=np.where(ages>=18, ages, -1)
#to preserve the shape of the array
print(adults)

[[21 -1 19 20 28 30 65 -1]
 [39 22 -1 18 19 99 20 32]]


In [ ]:
#Random Number Generation (RNG)
rng=np.random.default_rng(seed=1)
print(rng.integers(low=1, high=101, size=(5,2)))

[[48 52]
 [76 96]
 [ 4 15]
 [83 95]
 [25 32]]


In [ ]:
rng=np.random.default_rng()
array=np.array([1,2,3,4,5,6])
rng.shuffle(array)
print(array)

[2 1 4 5 3 6]


In [ ]:
rng=np.random.default_rng()
fruits=np.array(["apple", "banana", "cherry", "dragon-fruit", "grapes"])
print(fruits)
fruitS=rng.choice(fruits, size=2)
print(fruitS) 

['apple' 'banana' 'cherry' 'dragon-fruit' 'grapes']
['grapes' 'banana']


In [ ]:
print(np.random.uniform(low=1, high=4, size=3 ))

[3.14909718 2.38314918 2.32018009]
